### ISSUE TITLE
Russian & Bantu Gender & Phonological Properties

### ISSUE THREAD

**Issue by JohnGHutchinson** [grambank/grambank#33]
I'm just querying the coding of Russian for feature GB192. It's currently 0 but I would have thought it should be 1. To focus on one part of the paradigm, nouns whose nominative singular end in a hard consonant (class I) are masculine, with no apparent exceptions. Nouns whose nominative singular ends in -o or -e are typically neuter, or if they are not (true only of borrowings) they are indeclinable. Nouns whose nominative singular ends in a hard consonant plus -a are pretty much by default feminine but can being masculine if they refer to male persons e.g. in personal names. It's only nouns ending in a soft consonant or a soft consonant plus -a that can be of any gender, although in the case of the neuters of the latter class they are distinguished by extending the root outside of the nominative and accusative singular e.g. vremja~vremeni 'time'.

Other parts of the paradigm have similar kinds of correlations, e.g. a genitive singular with -a/-ja being pretty much exclusively found with masculines and neuters, while genitive plural in -ov being almost exclusively masculine with a handful of neuters (based on the discussion in Cubberly (2002): https://books.google.co.uk/books/about/Russian.html?id=yOGzAyN3V88C&redir_esc=y).

It's not a perfect correlation to be sure but it is there, and the wording of criterion 4 'if there seems to be a correlation between a noun's noun class/gender and specific phonological properties of the noun' would suggest to me that perfect alingment is not required. That Ukrainian and Belarussian have been listed as 1 for this feature for what appear to me at least to be similarly structured nominal paradigms is I think telling.

By the same token, I'm not entirely sure why such a large number of Bantu languages such as Ganda, Umbundu, Shona and Makhuwa have been counted as 0 by this criterion as well. Is there something about these languages' noun class systems that is different to those of e.g. Xhosa, Sango and Eastern Kikongo which are listed as 1 on this map?

**Comment by HedvigS** [comment]
Dear John, 

We will look into this and get back to you. The more specific languages you list, the easier it will be for us to tackle.

**Comment by Jaylatarche** [comment]
Hiya John and @HedvigS,

I have had a look into Russian based on the above information you have shared with us and also using a recent grammar from 2020 as I was unable to access Cubberly (2002). 

I'm in agreement that GB192 should be coded 1 for this feature. There is definitely a connection between the noun endings and the gender assignment. Wade 2020:55 has a nice list of examples that further demonstrate that nouns ending in a hard consonant are masculine. Wade2020:56-57 has examples of feminine assignments based on noun endings. I'd suggest that we correct the coding for this and can use the sources above as reference. 

In regards to the Bantu languages you have mentioned above. When coding GB192 and other features in Grambank, it is important for us to acknowledge that the coding decisions rely on linguistic research accessible to us. In cases where there are no explicit examples or descriptions provided in the grammar sources, we may code the feature as "?" until further information becomes available. We are unable to make generalisations solely based on  classifications within the same language family. Bantu languages may exhibit unique characteristics, and so our coding decisions are made on a language-specific basis, taking into account the available linguistic data for each individual language. 

I am going to have a look into the languages you have mentioned (Ganda, Umbundu, Shona and Makhuwa) and will update in this thread. 

Thanks!

**Comment by Jaylatarche** [comment]
Ganda GB192: Coded ? 

Looking at the most recently available grammar which is Katamba, Francis. 1974. Aspects of the Grammar of Luganda. (Doctoral dissertation, University of Edinburgh; 332pp.). There is mention of noun classes throughout the grammar, but only a brief mention of phonological conditioning in which the author states:

“No attempt has been made to show phonologically conditioned alternation in the realisation of prefixes and the list of suppletive classes of prefixes is not exhaustive.”

This indicates that the author hasn’t provided enough information on whether there are phonologically conditioned assignments. Without explicit information or examples, it is difficult to determine GB192 based on the available information. 

Looking at the grammar Ashton, E.O. and Mulira, E.M.K. and Ndawula, E. G. M. 1954. A Luganda grammar. London: Longmans, Green and Co. ix+516pp. Page 24 discusses the concords and prefixes used in different noun classes, including those with nasal prefixes. However, it doesn’t clearly indicate whether the assignment of noun classes is based on specific phonological properties of the nouns.

It's not clear enough to show a direct correlation, further info or examples are needed to show a clear preference for certain nouns to be classified in certain classes due to their phonological properties. 

Umbundu GB192: Coded 0 

Schadeberg_umbundu1990 has a small sketch on noun classes, but as with Ganda above, the information does not explicitly mention whether the assignment of noun classes is based on specific phonological properties of the nouns. Looking at an older grammar (Hambly 1934) the listed examples are numerous once again, but it is challenging to determine whether there is phonological conditioning based on the examples alone and there is no overt mention. Finally, looking at the grammar used by the coders of this sheet (Stover 1885) the pages they reference (13-15)  again indicate little information. Beyond their referenced pages (page 19) there is a brief mention of phonological changes which could indicate a potential correlation between the noun's phonological properties and its class assignment. However, it's important to note that the information provided does not cover all noun classes nor show enough information for us to determine. The current coding is 0, I would suggest ? 

Shona: Coded 0
Looking at the source the coder has used there’s evidence of a correlation between the phonological properties of nouns and their noun class assignment. On page 91, there are prefix variations and phonological changes in class 11 nouns, as well as the formation of plural forms in class 10. This suggests that phonological properties play a role in determining noun class/gender but I would prefer that the patron have a look over if possible! 

Makhuwa: Coded 0

Looking through the grammar used to decide this coding, it seems quite clear from the example and author’s description that the correct coding is 0. 

@hjhaynie apologies for this wall of text! Do you mind having a brief look over and giving a second opinion please? Many thanks!

**Comment by HedvigS** [comment]
Ping @hjhaynie

**Comment by hjhaynie** [comment]
Jay, thanks for jumping in! That is a very helpful wall of text, and in general I agree with your summary of the mentioned languages.

Russian is a clear 1, I agree.

For Bantu, there are striking sound patterns that arise from the class prefixes themselves, so it's important to focus on the properties of the nominal roots and what seem to be the organizing principles around which nominals are assigned to classes.

Ganda is currently coded ? and I do not see any evidence in the available grammars that would motivate a 1. Given that there are multiple descriptions of this language that describe semantic properties of the noun classes quite clearly and no descriptions that show any clear phonological properties of nominals that determine their classification, the evidence available makes this language seem quite similar to the other Bantu languages on this list to be revisited (which are coded 0).

For Umbundu I've looked at the mentioned grammars, and cannot see any indication that the classes in this language are organized around the phonological properties of roots/stems. The phonological information in Stover 1885 appears to describe allomorphic variation in prefixes, and my interpretation is that these alternations occur in the context of certain sounds (i.e. not that the nominal roots that combine with the relevant prefixes systematically contain those sounds). Again, the examples don't provide enough information to evaluate potential patterns. I would accept a change to ?, but I think we should be consistent in using 0 and ? across these languages if we edit original coding, and 0 seems consistent with how we've coded other languages that have similar evidence for GB192.

For Shona, the only phonological pattern that is obvious to me is that a set of nominal stems beginning in /ru/ that can be pluralized with the class 10 prefix. The grammar explains that these are morphologically complex, and ru- is the class 11 prefix. Again, I see evidence of phonological alternations at morpheme boundaries, but not phonological properties serving as an organizing principle for any particular noun class. I'm not in favor of overturning the coding.

Makhuwa seems quite similar to the other Bantu languages discussed in this issue, in terms of what is described (classes that are linked to semantic properties or functions, phonological alternations at morpheme boundaries) and what isn't described (phonological properties around which some class(es) is/are organized). I agree that this is a 0.

**Comment by HedvigS** [comment]
@Jaylatarche or @JanisReimringer would you be able to go through and implement the changes discussed above?

**Comment by JanisReimringer** [comment]
> @Jaylatarche or @JanisReimringer would you be able to go through and implement the changes discussed above?

Yes, I can start implementing them tomorrow!

**Comment by HedvigS** [comment]
Thanks!
