### ISSUE TITLE
Indefinite articles in Chamorro?

### ISSUE THREAD

**Issue by OlenaShcherbakova** [grambank/grambank#47]
Chamorro (cham1312) is coded as "0" for GB021 (Do indefinite nominals commonly have indefinite articles?) based on Chung (2012).
I came across another source (Stolz 2012) that suggests that this languages does have indefinite articles. Not suggesting an immediate change of the feature, but it might be worth looking into further.

Reference
Stolz, T. (2012). The attraction of indefinite articles on the borrowing of Spanish un in Chamorro. Dynamics of contact-induced language change. Berlin: Mouton de Gryuter, 167-194.

**Comment by HedvigS** [comment]
Got it, thanks @OlenaShcherbakova 

@JacobMenschel do you want to double check?

**Comment by JacobMenschel** [comment]
Yep, I'll take a look at it tomorrow! 😁

**Comment by HedvigS** [comment]
@JacobMenschel excellent!!

**Comment by JacobMenschel** [comment]
Hi all, 
I've now taken a look at Stolz (2012) and it definitely looks like Chamorro does have this indefinite article. Since the paper focusses on its grammaticalization and concludes that this marker has in fact reached the "non-specific indefinite marker" stage, I think there is no doubt that this marker is sufficiently grammaticalized to be considered an indefinite article. But I do have to check with previous codings and others how they handled borrowings like this one. I do know that e.g. [sipa1247](https://glottolog.org/resource/languoid/id/sipa1247) has a borrowed comparative marker _mas_ from Spanish, and has been coded 1 for [GB276 ](https://github.com/grambank/Grambank/wiki/GB276) so I'd assume it's a similar thing here.  On the other hand, [para1311](https://glottolog.org/resource/languoid/id/para1311) has been coded 0 for [GB020](https://github.com/grambank/Grambank/wiki/GB020); in that case, the definite article was borrowed from Spanish. I'll ask what the others think.

@HedvigS Maybe it would be useful to have a wiki page specifically on how to deal with borrowings? Just an idea.

All the best,
Jacob M.

**Comment by HedvigS** [comment]
> @HedvigS Maybe it would be useful to have a wiki page specifically on how to deal with borrowings? Just an idea.
> 

I understand. Maybe we'll need to bring in patrons here.

The advice for borrowings already exists, it's this: https://github.com/grambank/grambank/wiki/Language-internal-variation-and-different-strategies-for-one-function#borrowings

**Comment by JacobMenschel** [comment]
Good to know that that page exists, mea culpa! I suppose it didn't show up when searching for it.

Best
