### ISSUE TITLE
Presence of definite articles in Odia?

### ISSUE THREAD

**Issue by OlenaShcherbakova** [grambank/grambank#48]
Odia (oriy1255) is coded "1" for the presence of definite articles (GB020) based on Neukom and Patnaik (2003: 23-34). 
However, on p. 25-26, the authors of this grammar write:
"The suffixes -éta / -éti are referred to as "definite articles" or "enclitic definitives" in the literature. [...] There are, however, four arguments that show that the affixes -éta / -éti have only little to do with definiteness.
(i) The articles are used in combination with the indefinite suffix [...]
(ii) The articles can occur with indefinite pronouns [...]
(iii) There are even (rare) instances where a noun in indefinite use is marked by the articles [...]
(iv) In many clearly definite contexts no articles are used."
Worth further consideration :)

**Comment by JacobMenschel** [comment]
This is true, cf. also Neukom and Patnaik (2003: 24): "It will be shown that this label [i.e. "definite article"] is misleading. I will change GB020 accordingly and provide a comment.
I will also change GB021 from 0 to 1. The authors write "In all these cases [i.e. of the suffix _-e_ appearing], except for the numerals, the suffix _-e_ makes the referent indefinite." GB023 will remain 1, since _-e_ is a postnominal article. 

Thank you!
