### ISSUE TITLE
GB118 is positive for English, should be negative

### ISSUE THREAD

**Issue by Kiluvp** [grambank/grambank#60]
- **Feature GB118**: Are there serial verb constructions?
- **Language**: English, stan1293
- The sources cited for positive evidence for serial verb constructions ([Huddleston and Pullum 2002](https://grambank.clld.org/sources/gHuddlestonPullumEnglish): 51, 103, 113) all point to auxiliaries rather than serial verbs. According to the definition, if one verb of a series is inflected, all verbs of the series should be inflected, which is not the case for English auxiliaries plus main verbs.
- I know English well and know a lot about SVCs and other multiverb constructions (I'm a professor of linguistics)
- The same source that is cited supports my claim.

**Comment by HedvigS** [comment]
Dear @Kiluvp 

Thank you for your message.

This data point has been discussed a fair bit internally and also with people external to the project. We've re-evaluated it before. I appreciate your input, we will take it up again.

Besides ([Huddleston and Pullum 2002](https://grambank.clld.org/sources/gHuddlestonPullumEnglish) we also consider:

Haspelmath (2016:298)
 "A limiting case is English, which can combine the verbs go and come in imperatives and a restricted range of other environments (e.g. Go get the milk; Come eat with me; see Pullum 1990). Since the second slot is an open class, this is a productive construction and counts as an SVC by my definition."

**Comment by HedvigS** [comment]
Dear @Kiluvp . We've talked back and forth about this data-point in the past, and we're doing so again now. It's a tricky issue, with several different definitions of serial verbs existing and many grammars not being specific enough. We try as best we can do be consistent, so if we read what we've read about English but it concerned a minority language we'd treat it the same way.

The matter now lies with the feature patrons, @Jaylatarche and @JeremyCollinsMPI 

Until it's resolved, I have turned it into `?`.

**Comment by Kiluvp** [comment]
Thanks, Hedvig!

**Comment by HedvigS** [comment]
@Jaylatarche and @JeremyCollinsMPI . I've turned the data-point into `?`. Should I turn it to `1` or `0`?

**Comment by JeremyCollinsMPI** [comment]
Hi @Kiluvp , the issue for English was constructions such as 'go get food', 'come see this' and so on, but this may be limited to a set of motion verbs.  We are updating the definition to require SVCs to be more productive beyond a restricted set of verbs, and English will be coded as 0.

**Comment by Kiluvp** [comment]
That sounds reasonable!

Best,
Kilu
